version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - npm install -g sonarqube-scanner
        - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=d956cfddc710cb7c2d7746b68628e5424b265705 
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
